version: '3.8'

services:
  bitpin-producer:
    build:
      context: .
      dockerfile: Dockerfile.bitpin
    image: bitpin-producer:latest
    container_name: bitpin-producer
    restart: unless-stopped
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER:-localhost:9092}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DATA_DIR=/app/data
    volumes:
      - ./bitpin-data:/app/data
  wallex-trades:
    build:
      context: .
      dockerfile: Dockerfile.wallex
    image: wallex-producer:latest
    container_name: wallex-trades
    restart: unless-stopped
    network_mode: "host"
    environment:
      - KAFKA_BROKER=localhost:9092
      - LOG_LEVEL=info
    command: ["./wallex-producer", "-mode", "trades"]
  ramzinex-producer:
    build:
      context: .
      dockerfile: Dockerfile.ramzinex
    image: ramzinex-producer:latest
    container_name: ramzinex-producer
    restart: unless-stopped
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER:-localhost:9092}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DATA_DIR=/app/data
    volumes:
      - ./bitpin-data:/app/data
  tabdeal-producer:
    build:
      context: .
      dockerfile: Dockerfile.tabdeal
    image: tabdeal-producer:latest
    container_name: tabdeal-producer
    restart: unless-stopped
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER:-localhost:9092}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DATA_DIR=/app/data
    volumes:
      - ./ramzinex-data:/app/data
